// =========================================
// MICROSTOCK COMPLIANCE DICTIONARY
// For Adobe Stock, Shutterstock, Freepik, iStock, Vecteezy, Canva, Dreamstime
// =========================================

export const BANNED_STYLE_PHRASES = [
  'in the style of',
  'inspired by',
  'drawing on',
  'influenced by',
  'traditional of',
  'based on',
  'reminiscent of',
  'similar to',
  'like',
  'after the manner of'
];

export const BANNED_FICTIONAL_NAMES = [
  'mickey mouse', 'minnie mouse', 'donald duck', 'goofy', 'pluto',
  'simba', 'elsa', 'anna', 'olaf', 'woody', 'buzz lightyear',
  'nemo', 'dory', 'lightning mcqueen',
  'batman', 'superman', 'wonder woman', 'flash', 'aquaman', 'joker', 'harley quinn',
  'spiderman', 'spider-man', 'iron man', 'captain america', 'thor', 'hulk',
  'black widow', 'deadpool', 'wolverine', 'thanos', 'doctor strange',
  'ant-man', 'black panther', 'scarlet witch', 'loki', 'hawkeye',
  'naruto', 'goku', 'vegeta', 'luffy', 'zoro', 'natsu', 'ichigo',
  'gon', 'killua', 'sailor moon', 'totoro', 'no-face', 'spirited away',
  'pokemon', 'pikachu', 'charizard', 'mewtwo', 'digimon', 'evangelion', 'gundam',
  'mario', 'luigi', 'peach', 'bowser', 'link', 'zelda', 'ganon',
  'sonic', 'tails', 'knuckles', 'kirby', 'metroid', 'samus',
  'master chief', 'cortana', 'cloud strife', 'sephiroth', 'pac-man',
  'donkey kong', 'yoshi', 'wario', 'waluigi', 'kratos', 'lara croft',
  'harry potter', 'hermione', 'ron weasley', 'voldemort', 'dumbledore',
  'darth vader', 'yoda', 'luke skywalker', 'princess leia', 'han solo',
  'chewbacca', 'stormtrooper', 'godzilla', 'king kong', 'jurassic park',
  'transformers', 'optimus prime', 'megatron', 'ghostbusters', 'terminator',
  'robocop', 'alien', 'xenomorph', 'predator', 'freddy krueger',
  'jason voorhees', 'michael myers', 'chucky', 'pennywise',
  'spongebob', 'patrick star', 'squidward', 'mr krabs',
  'homer simpson', 'bart simpson', 'lisa simpson', 'marge simpson',
  'peter griffin', 'stewie griffin', 'brian griffin', 'lois griffin',
  'shrek', 'fiona', 'donkey', 'puss in boots'
];

export const BANNED_CELEBRITIES = [
  'taylor swift', 'beyonce', 'rihanna', 'adele', 'bruno mars',
  'justin bieber', 'ariana grande', 'billie eilish', 'drake',
  'kanye west', 'jay-z', 'kendrick lamar', 'the weeknd', 'dua lipa',
  'olivia rodrigo', 'harry styles', 'ed sheeran', 'selena gomez',
  'katy perry', 'lady gaga', 'madonna', 'michael jackson', 'prince',
  'whitney houston', 'elvis presley', 'freddie mercury', 'david bowie',
  'john lennon', 'paul mccartney', 'bob dylan',
  'leonardo dicaprio', 'brad pitt', 'tom cruise', 'will smith',
  'robert downey', 'chris hemsworth', 'chris evans', 'chris pratt',
  'scarlett johansson', 'angelina jolie', 'jennifer lawrence',
  'emma stone', 'emma watson', 'natalie portman', 'meryl streep',
  'denzel washington', 'morgan freeman', 'samuel l jackson', 'tom hanks',
  'johnny depp', 'matt damon', 'ben affleck', 'george clooney',
  'ryan reynolds', 'mark ruffalo', 'jeremy renner', 'anthony mackie',
  'chadwick boseman', 'idris elba', 'keanu reeves', 'harrison ford',
  'mrbeast', 'pewdiepie', 'logan paul', 'jake paul', 'ksi',
  'ninja', 'pokimane', 'valkyrae', 'dream', 'tommyinnit', 'tubbo',
  'lionel messi', 'cristiano ronaldo', 'neymar', 'mbappe', 'haaland',
  'lebron james', 'stephen curry', 'kevin durant', 'giannis',
  'tom brady', 'patrick mahomes', 'usain bolt', 'serena williams',
  'roger federer', 'rafael nadal', 'novak djokovic', 'tiger woods',
  'elon musk', 'steve jobs', 'bill gates', 'jeff bezos',
  'mark zuckerberg', 'larry page', 'sergey brin', 'tim cook',
  'satya nadella', 'jack ma', 'richard branson', 'warren buffett',
  'oprah winfrey', 'kim kardashian', 'kylie jenner', 'paris hilton',
  'britney spears', 'jennifer lopez', 'shakira', 'eminem', 'snoop dogg'
];

export const BANNED_ARTISTS = [
  'leonardo da vinci', 'michelangelo', 'raphael', 'donatello',
  'botticelli', 'titian', 'caravaggio', 'rembrandt', 'van gogh',
  'monet', 'picasso', 'dali', 'warhol', 'pollock', 'renoir',
  'degas', 'cezanne', 'gauguin', 'matisse', 'kandinsky', 'klee',
  'mondrian', 'magritte', 'escher', 'hopper', 'rockwell',
  'o\'keeffe', 'cassatt', 'sargent', 'whistler', 'turner',
  'constable', 'friedrich', 'delacroix', 'goya', 'velazquez',
  'el greco', 'bruegel', 'bosch', 'durer', 'holbein', 'rubens',
  'vermeer', 'hals', 'steens', 'ruysdael', 'hobbema', 'cuyp',
  'claude lorrain', 'nicolas poussin', 'la tour', 'greuze',
  'fragonard', 'boucher', 'watteau', 'lancret', 'pater',
  'nattier', 'largilliere', 'rigaud', 'tocque', 'drouais',
  'duplessis', 'callet', 'menageot', 'regnault', 'david', 'gros',
  'gerard', 'guerin', 'delaroche', 'vernet', 'delacroix',
  'gericault', 'ingres', 'flandrin', 'cabanel', 'bouguereau',
  'meissonier', 'detaille', 'neuville', 'beraud', 'breton',
  'millet', 'courbet', 'daubigny', 'rousseau', 'diaz', 'dupre',
  'troyon', 'jacque', 'corot', 'manet', 'pisarro', 'sisley',
  'morisset', 'bazille', 'fantin-latour', 'guillaumin', 'cebot',
  'boudin', 'jongkind', 'berthe morisot', 'eva gonzales',
  'mary cassatt', 'childe hassam', 'john singer sargent',
  'winslow homer', 'thomas eakins', 'henry ossawa tanner',
  'robert henri', 'john sloan', 'george bellows', 'everett shinn',
  'william glackens', 'ernest lawson', 'maurice prendergast',
  'arthur dove', 'marsden hartley', 'georgia o\'keeffe',
  'charles demuth', 'charles sheeler', 'stuart davis', 'max weber',
  'oskar kokoschka', 'egon schiele', 'gustav klimt', 'alfred kubin',
  'koloman moser', 'josef hoffmann', 'otto wagner', 'adolf loos'
];

export const BANNED_MOVIE_FRANCHISES = [
  'star wars', 'star trek', 'marvel cinematic universe', 'mcu',
  'dc extended universe', 'dceu', 'harry potter', 'wizarding world',
  'fantastic beasts', 'lord of the rings', 'lotr', 'middle earth',
  'the hobbit', 'game of thrones', 'thrones', 'westeros',
  'hunger games', 'panem', 'twilight', 'forks', 'divergent',
  'maze runner', 'percy jackson', 'camp half-blood',
  'chronicles of narnia', 'narnia', 'golden compass',
  'his dark materials', 'jurassic park', 'jurassic world',
  'indiana jones', 'pirates of the caribbean', 'transformers',
  'fast and furious', 'mission impossible', 'john wick',
  'the matrix', 'matrix', 'alien', 'predator', 'terminator',
  'robocop', 'highlander', 'underworld', 'resident evil',
  'silent hill', 'final destination', 'scream', 'halloween',
  'friday the 13th', 'nightmare on elm street', 'texas chainsaw massacre',
  'psycho', 'the shining', 'it', 'the conjuring', 'insidious',
  'sinister', 'purge', 'human centipede', 'saw', 'hostel',
  'wrong turn', 'deliverance', 'duel', 'jaws', 'et',
  'close encounters', 'war of the worlds', 'independence day',
  'district 9', 'arrival', 'blade runner', 'total recall',
  'minority report', 'ready player one', 'tron', 'wreck-it ralph',
  'big hero 6'
];

export const BANNED_ANIME_SERIES = [
  'naruto', 'one piece', 'dragon ball', 'dragon ball z',
  'dragon ball super', 'attack on titan', 'shingeki no kyojin',
  'death note', 'fullmetal alchemist', 'demon slayer',
  'kimetsu no yaiba', 'my hero academia', 'boku no hero academia',
  'hunter x hunter', 'jujutsu kaisen', 'tokyo ghoul', 'bleach',
  'one punch man', 'mob psycho 100', 'fire force', 'black clover',
  'fairy tail', 'seven deadly sins', 'nanatsu no taizai',
  'sword art online', 're zero', 'konosuba', 'overlord',
  'that time i got reincarnated as a slime', 'tensei shitara slime datta ken',
  'rising of the shield hero', 'goblin slayer', 'dr stone',
  'promised neverland', 'yakusoku no neverland', 'vinland saga',
  'berserk', 'vagabond', 'haikyuu', 'kuroko no basket',
  'slam dunk', 'prince of tennis', 'yugioh', 'yu-gi-oh',
  'digimon', 'pokemon', 'beyblade', 'bakugan', 'medabots',
  'zoids', 'gundam', 'mobile suit gundam', 'evangelion',
  'neon genesis evangelion', 'code geass', 'steins gate',
  'monster', 'cowboy bebop', 'samurai champloo', 'trigun',
  'outlaw star', 'space dandy', 'redline', 'akira',
  'ghost in the shell', 'appleseed', 'dominion tank police',
  'bubblegum crisis', 'macross', 'robotech', 'voltron',
  'getter robo', 'mazinger', 'great mazinger', 'grendizer'
];

export const BANNED_GAME_FRANCHISES = [
  'super mario', 'mario kart', 'mario party', 'paper mario',
  'luigi\'s mansion', 'donkey kong', 'the legend of zelda',
  'zelda', 'metroid', 'kirby', 'star fox', 'star craft',
  'diablo', 'overwatch', 'hearthstone', 'world of warcraft',
  'warcraft', 'final fantasy', 'kingdom hearts', 'dragon quest',
  'chrono trigger', 'secret of mana', 'trials of mana',
  'heroes of mana', 'children of mana', 'adventures of mana',
  'rise of mana', 'echoes of mana', 'vision of mana',
  'legend of mana', 'dawn of mana', 'sword of mana',
  'friends of mana', 'circle of mana', 'power of mana',
  'spirit of mana', 'heart of mana', 'soul of mana',
  'mind of mana', 'body of mana', 'essence of mana',
  'tree of mana', 'seed of mana', 'flower of mana',
  'fruit of mana', 'leaf of mana', 'root of mana',
  'stem of mana', 'branch of mana', 'twig of mana',
  'bud of mana', 'bloom of mana', 'petal of mana',
  'pollen of mana', 'nectar of mana', 'honey of mana',
  'bee of mana', 'hive of mana', 'queen of mana',
  'king of mana', 'prince of mana', 'princess of mana',
  'duke of mana', 'count of mana', 'baron of mana',
  'lord of mana', 'lady of mana', 'knight of mana',
  'pawn of mana', 'rook of mana', 'bishop of mana',
  'jack of mana', 'ace of mana', 'joker of mana',
  'fool of mana', 'magician of mana', 'priestess of mana',
  'empress of mana', 'emperor of mana', 'hierophant of mana',
  'lovers of mana', 'chariot of mana', 'strength of mana',
  'hermit of mana', 'wheel of fortune of mana', 'justice of mana',
  'hanged man of mana', 'death of mana', 'temperance of mana',
  'devil of mana', 'tower of mana', 'star of mana',
  'moon of mana', 'sun of mana', 'judgement of mana',
  'world of mana', 'yo-kai watch', 'cardfight vanguard',
  'buddyfight', 'future card buddyfight', 'weiss schwarz',
  'warhammer', 'warhammer 40k', 'age of sigmar',
  'warmachine', 'hordes', 'warmahordes', 'infinity',
  'malifaux', 'guild ball', 'blood bowl', 'necromunda',
  'kill team', 'warcry', 'soulbound', 'shadowrun',
  'battletech', 'mechanical assault', 'mechwarrior',
  'aero tech', 'dropship', 'jumpship', 'warship',
  'fighter', 'small craft', 'protomech', 'elemental',
  'battle armor', 'powered armor', 'exo skeleton',
  'cybernetics', 'augmentation', 'implant', 'prosthetic',
  'bionic', 'cyborg', 'android', 'robot', 'drone'
];

export const BANNED_BRANDS = [
  // Tech Brands
  'apple', 'iphone', 'ipad', 'ipod', 'macbook', 'imac',
  'mac pro', 'mac mini', 'airpods', 'apple watch',
  'samsung', 'galaxy', 'google', 'pixel', 'nest',
  'chromecast', 'microsoft', 'surface', 'xbox',
  'windows', 'office', 'sony', 'playstation', 'ps5',
  'ps4', 'ps3', 'ps2', 'ps vita', 'psp', 'vaio',
  'walkman', 'nintendo', 'switch', 'wii', 'ds', '3ds',
  'game boy', 'gamecube', 'n64', 'snes', 'nes',
  'virtual boy', 'wii u', 'sega', 'genesis', 'dreamcast',
  'saturn', 'master system', 'game gear', 'atari',
  '2600', '5200', '7800', 'jaguar', 'lynx', 'neo geo',
  'snk', 'capcom', 'square enix', 'konami', 'namco',
  'bandai', 'tomy', 'hasbro', 'mattel', 'lego',
  'barbie', 'hot wheels', 'matchbox', 'fisher-price',
  ' Playskool', 'little tikes', 'vtech', 'leapfrog',
  'oregon scientific', 'tiger electronics', 'milton bradley',
  'parker brothers', 'wizards of the coast', 'dungeons & dragons',
  'magic the gathering', 'pokemon cards', 'yugioh cards',
  'nerf', 'water warriors', 'super soaker', 'buzz bee toys',
  // Fashion Brands
  'nike', 'adidas', 'puma', 'reebok', 'under armour',
  'new balance', 'converse', 'vans', 'timberland',
  'dr martens', 'clarks', 'crocs', 'birkenstock', 'ugg',
  'sorel', 'columbia', 'the north face', 'patagonia',
  'arcteryx', 'mammut', 'salomon', 'merrell', 'keen',
  'caterpillar', 'cat', 'wolverine', 'dickies', 'carhartt',
  'duluth trading', 'll bean', 'eddie bauer', 'lands\' end',
  'j crew', 'banana republic', 'gap', 'old navy',
  'athleta', 'piperlime', 'intermix', 'hill city',
  'janie and jack', 'bode', 'row', 'vince', 'theory',
  'equipment', 'joie', 'current/elliott', 'rag & bone',
  'alexander wang', 'proenza schouler', 'altuzarra',
  'thakoon', 'jason wu', 'derek lam', 'tory burch',
  'michael kors', 'coach', 'kate spade', 'dooney & bourke',
  'fossil', 'marc jacobs', 'rebecca minkoff', 'milly',
  'alice + olivia', 'diane von furstenberg', 'vera wang',
  'carolina herrera', 'oscar de la renta', 'ralph lauren',
  'tommy hilfiger', 'calvin klein', 'donna karan',
  'liz claiborne', 'ellen tracy', 'anne klein',
  'jones new york', 'nine west', 'naturalizer',
  'easy spirit', 'rockport', 'born', 'sofft', 'vionic',
  'orthaheel', 'aetrex', 'finn comfort', 'mephisto',
  'wolky', 'rieker', 'ara', 'caprice', 'gabor',
  'think', 'waldlaufer', 'remonte', 'dorndorf', 'jana',
  'marco tozzi', 'bugatti shoes', 'lloyd', 'paul green',
  'stuart weitzman', 'jimmy choo', 'manolo blahnik',
  'christian louboutin', 'roger vivier', 'salvatore ferragamo',
  'tod\'s', 'hogan', 'prada', 'gucci', 'fendi',
  'bottega veneta', 'balenciaga', 'saint laurent', 'celine',
  'givenchy', 'chanel', 'dior', 'louis vuitton', 'hermes',
  'burberry', 'mulberry', 'anya hindmarch', 'sophia webster',
  'charlotte olympia', 'nicholas kirkwood', 'gianvito rossi',
  'aquazzura', 'casadei', 'rene caovilla', 'giuseppe zanotti',
  'sergio rossi', 'pollini', 'alberto moretti', 'le silla',
  'nero giardini', 'geox', 'superga', 'diadora', 'fila',
  'lotto', 'kappa', 'ellesse', 'robe di kappa',
  // Food & Beverage Brands
  'coca-cola', 'coke', 'pepsi', 'sprite', 'fanta',
  'mountain dew', 'dr pepper', '7up', 'red bull',
  'monster', 'rockstar', 'bang', 'celcius', 'starbucks',
  'dunkin', 'tim hortons', 'mcdonalds', 'burger king',
  'wendy\'s', 'subway', 'kfc', 'pizza hut', 'domino\'s',
  'papa john\'s', 'taco bell', 'chipotle', 'five guys',
  'in-n-out', 'shake shack', 'white castle', 'sonic',
  'dairy queen', 'baskin robbins', 'ben & jerry\'s',
  'haagen-dazs', 'nestle', 'kellogg\'s', 'general mills',
  'post', 'quaker', 'mars', 'hershey\'s', 'cadbury',
  'ferrero', 'nutella', 'oreo', 'chips ahoy', 'ritz',
  'triscuit', 'wheat thins', 'cheez-it', 'goldfish',
  'pringles', 'lays', 'doritos', 'cheetos', 'fritos',
  'ruffles', 'kettle brand', 'cape cod', 'timm\'s',
  'late july', 'food should taste good', 'garden of eatin',
  'terra', 'bare', 'kind', 'nature valley', 'clif bar',
  'larabar', 'rxbar', 'pure protein', 'think thin',
  'quest nutrition', 'atkins', 'south beach diet',
  'weight watchers', 'jenny craig', 'nutrisystem',
  'optavia', 'noom', 'myfitnesspal', 'lose it',
  // Auto Brands
  'toyota', 'honda', 'nissan', 'mazda', 'subaru',
  'mitsubishi', 'suzuki', 'isuzu', 'bmw', 'mercedes',
  'audi', 'volkswagen', 'vw', 'porsche', 'ferrari',
  'lamborghini', 'maserati', 'alfa romeo', 'fiat',
  'lancia', 'ford', 'chevrolet', 'cadillac', 'buick',
  'gmc', 'dodge', 'chrysler', 'jeep', 'ram', 'tesla',
  'rivian', 'lucid', 'polestar', 'volvo', 'saab',
  'jaguar', 'land rover', 'range rover', 'bentley',
  'rolls-royce', 'aston martin', 'lotus', 'mclaren',
  'koenigsegg', 'bugatti', 'pagani', 'hyundai', 'kia',
  'genesis', 'lexus', 'infiniti', 'acura', 'lincoln',
  // Camera Brands
  'canon', 'nikon', 'sony', 'fujifilm', 'panasonic',
  'olympus', 'leica', 'hasselblad', 'phase one',
  'sigma', 'tamron', 'tokina', 'samyang', 'rokinon',
  'voigtlander', 'zeiss', 'schneider', 'rodagon',
  'komura', 'vivitar', 'sun', 'pentax', 'ricoh',
  'casio', 'epson', 'hp',
  // Other Major Brands
  'amazon', 'prime', 'aws', 'alexa', 'echo', 'kindle',
  'fire tv', 'ring', 'blink', 'eero', 'whole foods',
  'fresh', 'go', 'books', 'music', 'video', 'gaming',
  'twitch', 'imdb', 'goodreads', 'audible', 'zappos',
  'shopbop', 'east dane', 'myhabit', 'woot', 'fabric',
  'lab126', 'kuiper', 'project kuiper', 'blue origin',
  'new shepard', 'new glenn', 'orbital reef', 'bezos',
  'spacex', 'falcon', 'dragon', 'starship', 'starlink',
  'hyperloop', 'boring company', 'neuralink', 'openai',
  'gpt', 'chatgpt', 'dall-e', 'midjourney',
  'stable diffusion', 'runway', 'pika', 'synthesia',
  'heygen', 'descript', 'elevenlabs', 'anthropic',
  'claude', 'google deepmind', 'gemini', 'bard',
  'vertex', 'colab', 'tensorflow', 'pytorch', 'jax',
  'flax', 'haiku', 'imagen', 'videopoet', 'lumiere',
  'alphago', 'alphazero', 'alphafold', 'waymo', 'wing',
  'verily', 'calico', 'x development', 'moonshot',
  'loon', 'sidekick', 'nest labs', 'dropcam', 'revolv',
  'thread', 'woven', 'capitalg', 'gradient', 'area 120',
  'jigsaw', 'chronicle', 'shield', 'onhub', 'daydream',
  'cardboard', 'tango', 'project ara', 'glass', 'wave',
  'jump', 'spotlight stories', 'tilt brush', 'blocks',
  'quill', 'medium', 'oculus', 'quest', 'rift', 'go',
  'air', 'pro', 'horizon', 'venues', 'rooms', 'home',
  'workrooms', 'infinite office', 'casting', 'link',
  'dash', 'browser', 'tv', 'gaming', 'studios', 'sound',
  'touch', 'remote', 'controller', 'sensors', 'insight',
  'tracking', 'passthrough', 'mixed reality',
  'augmented reality', 'virtual reality', 'extended reality',
  'metaverse', 'webxr', 'openxr', 'vulkan', 'opengl',
  'directx', 'metal', 'cuda', 'optix', 'physx', 'flex',
  'blast', 'destruction', 'clothing', 'hair', 'flow',
  'apex', 'gameworks', 'deeplearning', 'ai', 'research',
  'labs', 'institute', 'foundation', 'initiative',
  'partnership', 'alliance', 'consortium', 'coalition',
  'network', 'platform', 'ecosystem', 'marketplace',
  'store', 'shop', 'mall', 'plaza', 'center', 'hub',
  'zone', 'district', 'quarter', 'village', 'town',
  'city', 'metro', 'urban', 'suburban', 'rural',
  'remote', 'online', 'digital', 'virtual', 'cloud',
  'edge', 'fog', 'mesh', 'net', 'web', 'internet',
  'intranet', 'extranet', 'lan', 'wan', 'man', 'pan',
  'san', 'can', 'dan', 'ean', 'fan', 'gan', 'han',
  'ian', 'jan', 'kan', 'lan', 'man', 'nan', 'oan',
  'pan', 'qan', 'ran', 'san', 'tan', 'uan', 'van',
  'wan', 'xan', 'yan', 'zan'
];

export const BANNED_NEWS_EVENTS = [
  'breaking news', 'just in', 'developing story',
  'live coverage', 'exclusive report', 'investigative report',
  'special report', 'news alert', 'urgent update',
  'election', 'referendum', 'plebiscite', 'ballot',
  'vote', 'voting', 'poll', 'survey', 'census',
  'political campaign', 'presidential', 'congressional',
  'senatorial', 'gubernatorial', 'mayoral', 'parliamentary',
  'legislative', 'municipal', 'local election', 'state election',
  'national election', 'international election', 'primary',
  'caucus', 'convention', 'debate', 'town hall', 'rally',
  'protest', 'demonstration', 'march', 'sit-in', 'strike',
  'walkout', 'boycott', 'embargo', 'sanction', 'tariff',
  'trade war', 'economic sanction', 'diplomatic sanction',
  'military sanction', 'financial sanction', 'travel ban',
  'visa restriction', 'immigration ban', 'refugee crisis',
  'asylum seeker', 'illegal immigration', 'border crisis',
  'wall', 'fence', 'checkpoint', 'patrol', 'surveillance',
  'monitoring', 'tracking', 'screening', 'vetting',
  'background check', 'security clearance', 'investigation',
  'inquiry', 'probe', 'audit', 'review', 'inspection',
  'examination', 'analysis', 'evaluation', 'assessment',
  'study', 'research', 'report', 'finding', 'conclusion',
  'recommendation', 'proposal', 'initiative', 'program',
  'project', 'plan', 'strategy', 'policy', 'procedure',
  'protocol', 'guideline', 'standard', 'regulation', 'rule',
  'law', 'statute', 'ordinance', 'decree', 'mandate',
  'order', 'directive', 'instruction', 'command',
  'requirement', 'obligation', 'duty', 'responsibility',
  'accountability', 'liability', 'culpability', 'guilt',
  'innocence', 'verdict', 'judgment', 'sentence', 'penalty',
  'punishment', 'fine', 'fee', 'tax', 'levy', 'duty',
  'tariff', 'impost', 'tribute', 'toll', 'charge', 'cost',
  'price', 'rate', 'premium', 'deductible', 'copay',
  'coinsurance', 'coverage', 'benefit', 'compensation',
  'reimbursement', 'refund', 'rebate', 'discount', 'coupon',
  'voucher', 'credit', 'gift card', 'loyalty program',
  'rewards program', 'points', 'miles', 'cashback', 'bonus',
  'promotion', 'offer', 'deal', 'sale', 'clearance',
  'liquidation', 'bankruptcy', 'insolvency', 'receivership',
  'foreclosure', 'repossession', 'eviction', 'dispossession',
  'expropriation', 'nationalization', 'privatization',
  'deregulation', 'liberalization', 'globalization',
  'localization', 'regionalization', 'integration',
  'harmonization', 'standardization', 'normalization',
  'regularization', 'formalization', 'institutionalization',
  'bureaucratization', 'centralization', 'decentralization',
  'devolution', 'delegation', 'assignment', 'allocation',
  'distribution', 'dispersion', 'dissemination',
  'propagation', 'transmission', 'communication', 'broadcast',
  'publication', 'release', 'announcement', 'declaration',
  'statement', 'proclamation', 'manifesto', 'pledge',
  'promise', 'commitment', 'undertaking', 'engagement',
  'obligation', 'contract', 'agreement', 'accord', 'pact',
  'treaty', 'convention', 'protocol', 'memorandum',
  'understanding', 'arrangement', 'settlement', 'resolution',
  'solution', 'answer', 'response', 'reply', 'reaction',
  'feedback', 'comment', 'remark', 'observation', 'note',
  'memo', 'message', 'notification', 'alert', 'warning',
  'caution', 'advisory', 'bulletin', 'newsletter', 'digest',
  'summary', 'brief', 'overview', 'outline', 'synopsis',
  'abstract', 'extract', 'excerpt', 'quote', 'citation',
  'reference', 'source', 'origin', 'beginning', 'start',
  'commencement', 'initiation', 'launch', 'debut', 'premiere',
  'opening', 'unveiling', 'reveal', 'disclosure', 'exposure',
  'discovery', 'detection', 'identification', 'recognition',
  'acknowledgment', 'acceptance', 'approval', 'endorsement',
  'support', 'backing', 'sponsorship', 'patronage', 'advocacy'
];

// Combine all banned arrays for easy access
export const ALL_BANNED_TERMS = [
  ...BANNED_STYLE_PHRASES,
  ...BANNED_FICTIONAL_NAMES,
  ...BANNED_CELEBRITIES,
  ...BANNED_ARTISTS,
  ...BANNED_MOVIE_FRANCHISES,
  ...BANNED_ANIME_SERIES,
  ...BANNED_GAME_FRANCHISES,
  ...BANNED_BRANDS,
  ...BANNED_NEWS_EVENTS
];

// Regex patterns for detecting variations
export const COMPLIANCE_REGEX_PATTERNS = {
  styleVariations: /(?:pixar[- ]?style|disney[- ]?inspired|marvel[- ]?like|anime[- ]?style|ghibli[- ]?inspired|style[- ]?of|inspired[- ]?by|drawing[- ]?on|influenced[- ]?by|based[- ]?on|reminiscent[- ]?of|similar[- ]?to|after[- ]?the[- ]?manner[- ]?of)/gi,
  brandVariations: /(?:^|\s)(?:iphone|ipad|macbook|imac|airpods|playstation|xbox|nintendo|nike|adidas|puma|reebok|coca[- ]?cola|coke|pepsi|bmw|mercedes|audi|porsche|ferrari|lamborghini|toyota|honda|samsung|canon|nikon|sony|google|microsoft|lego|disney|marvel|star[- ]?wars)(?:s|'s|like|style|inspired|type|esque)?(?:\s|$)/gi,
  celebrityVariations: /(?:^|\s)(?:taylor[- ]?swift|elon[- ]?musk|mrbeast|lionel[- ]?messi|cristiano[- ]?ronaldo|beyonce|rihanna|adele|bruno[- ]?mars|justin[- ]?bieber|ariana[- ]?grande|billie[- ]?eilish|drake|kanye[- ]?west|jay[- ]?z|kendrick[- ]?lamar|the[- ]?weeknd|dua[- ]?lipa|olivia[- ]?rodrigo|harry[- ]?styles|ed[- ]?sheeran|selena[- ]?gomez|katy[- ]?perry|lady[- ]?gaga|madonna|michael[- ]?jackson|prince|whitney[- ]?houston|elvis[- ]?presley|freddie[- ]?mercury|david[- ]?bowie|john[- ]?lennon|paul[- ]?mccartney|bob[- ]?dylan)(?:'s|like|style|inspired)?(?:\s|$)/gi,
  fictionalVariations: /(?:^|\s)(?:mickey[- ]?mouse|minnie[- ]?mouse|donald[- ]?duck|goofy|pluto|simba|elsa|anna|olaf|woody|buzz[- ]?lightyear|nemo|dory|lightning[- ]?mcqueen|batman|superman|wonder[- ]?woman|flash|aquaman|joker|harley[- ]?quinn|spider[- ]?man|spiderman|iron[- ]?man|captain[- ]?america|thor|hulk|black[- ]?widow|deadpool|wolverine|thanos|doctor[- ]?strange|ant[- ]?man|black[- ]?panther|scarlet[- ]?witch|loki|hawkeye|naruto|goku|vegeta|luffy|zoro|natsu|ichigo|gon|killua|sailor[- ]?moon|totoro|no[- ]?face|spirited[- ]?away|pokemon|pikachu|charizard|mewtwo|digimon|evangelion|gundam|mario|luigi|peach|bowser|link|zelda|ganon|sonic|tails|knuckles|kirby|metroid|samus|master[- ]?chief|cortana|cloud[- ]?strife|sephiroth|pac[- ]?man|ghosts|donkey[- ]?kong|yoshi|wario|waluigi|kratos|lara[- ]?croft|doom[- ]?guy|spyro|crash[- ]?bandicoot|ratchet|clank|harry[- ]?potter|hermione|ron[- ]?weasley|voldemort|dumbledore|darth[- ]?vader|yoda|luke[- ]?skywalker|princess[- ]?leia|han[- ]?solo|chewbacca|stormtrooper|godzilla|king[- ]?kong|jurassic[- ]?park|transformers|optimus[- ]?prime|megatron|ghostbusters|terminator|robocop|alien|xenomorph|predator|freddy[- ]?krueger|jason[- ]?voorhees|michael[- ]?myers|chucky|pennywise|spongebob|patrick[- ]?star|squidward|mr[- ]?krabs|homer[- ]?simpson|bart[- ]?simpson|lisa[- ]?simpson|marge[- ]?simpson|peter[- ]?griffin|stewie[- ]?griffin|brian[- ]?griffin|lois[- ]?griffin|shrek|fiona|donkey|puss[- ]?in[- ]?boots|ogre)(?:'s|like|style|inspired)?(?:\s|$)/gi,
  mediaVariations: /(?:^|\s)(?:star[- ]?wars|star[- ]?trek|marvel[- ]?cinematic[- ]?universe|mcu|dc[- ]?extended[- ]?universe|dceu|harry[- ]?potter|wizarding[- ]?world|fantastic[- ]?beasts|lord[- ]?of[- ]?the[- ]?rings|lotr|middle[- ]?earth|the[- ]?hobbit|game[- ]?of[- ]?thrones|thrones|westeros|hunger[- ]?games|panem|twilight|forks|divergent|maze[- ]?runner|percy[- ]?jackson|camp[- ]?half[- ]?blood|chronicles[- ]?of[- ]?narnia|narnia|golden[- ]?compass|his[- ]?dark[- ]?materials|jurassic[- ]?park|jurassic[- ]?world|indiana[- ]?jones|pirates[- ]?of[- ]?the[- ]?caribbean|transformers|fast[- ]?and[- ]?furious|mission[- ]?impossible|john[- ]?wick|the[- ]?matrix|matrix|alien|predator|terminator|robocop|highlander|underworld|resident[- ]?evil|silent[- ]?hill|final[- ]?destination|scream|halloween|friday[- ]?the[- ]?13th|nightmare[- ]?on[- ]?elm[- ]?street|texas[- ]?chainsaw[- ]?massacre|psycho|the[- ]?shining|it|the[- ]?conjuring|insidious|sinister|purge|human[- ]?centipede|saw|hostel|wrong[- ]?turn|deliverance|duel|jaws|et|close[- ]?encounters|war[- ]?of[- ]?the[- ]?worlds|independence[- ]?day|district[- ]?9|arrival|blade[- ]?runner|total[- ]?recall|minority[- ]?report|ready[- ]?player[- ]?one|tron|wreck[- ]?it[- ]?ralph|big[- ]?hero[- ]?6)(?:'s|like|style|inspired)?(?:\s|$)/gi,
  newsEventPatterns: /(?:breaking[- ]?news|just[- ]?in|developing[- ]?story|live[- ]?coverage|exclusive[- ]?report|investigative[- ]?report|special[- ]?report|news[- ]?alert|urgent[- ]?update|election|referendum|plebiscite|ballot|vote|voting|poll|survey|census|political[- ]?campaign|presidential|congressional|senatorial|gubernatorial|mayoral|parliamentary|legislative|municipal|local[- ]?election|state[- ]?election|national[- ]?election|international[- ]?election|primary|caucus|convention|debate|town[- ]?hall|rally|protest|demonstration|march|sit[- ]?in|strike|walkout|boycott|embargo|sanction|tariff|trade[- ]?war|economic[- ]?sanction|diplomatic[- ]?sanction|military[- ]?sanction|financial[- ]?sanction|travel[- ]?ban|visa[- ]?restriction|immigration[- ]?ban|refugee[- ]?crisis|asylum[- ]?seeker|illegal[- ]?immigration|border[- ]?crisis|wall|fence|checkpoint|patrol|surveillance|monitoring|tracking|screening|vetting|background[- ]?check|security[- ]?clearance|investigation|inquiry|probe|audit|review|inspection|examination|analysis|evaluation|assessment|study|research|report|finding|conclusion|recommendation|proposal|initiative|program|project|plan|strategy|policy|procedure|protocol|guideline|standard|regulation|rule|law|statute|ordinance|decree|mandate|order|directive|instruction|command|requirement|obligation|duty|responsibility|accountability|liability|culpability|guilt|innocence|verdict|judgment|sentence|penalty|punishment|fine|fee|tax|levy|duty|tariff|impost|tribute|toll|charge|cost|price|rate|premium|deductible|copay|coinsurance|coverage|benefit|compensation|reimbursement|refund|rebate|discount|coupon|voucher|credit|gift[- ]?card|loyalty[- ]?program|rewards[- ]?program|points|miles|cashback|bonus|promotion|offer|deal|sale|clearance|liquidation|bankruptcy|insolvency|receivership|foreclosure|repossession|eviction|dispossession|expropriation|nationalization|privatization|deregulation|liberalization|globalization|localization|regionalization|integration|harmonization|standardization|normalization|regularization|formalization|institutionalization|bureaucratization|centralization|decentralization|devolution|delegation|assignment|allocation|distribution|dispersion|dissemination|propagation|transmission|communication|broadcast|publication|release|announcement|declaration|statement|proclamation|manifesto|pledge|promise|commitment|undertaking|engagement|obligation|contract|agreement|accord|pact|treaty|convention|protocol|memorandum|understanding|arrangement|settlement|resolution|solution|answer|response|reply|reaction|feedback|comment|remark|observation|note|memo|message|notification|alert|warning|caution|advisory|bulletin|newsletter|digest|summary|brief|overview|outline|synopsis|abstract|extract|excerpt|quote|citation|reference|source|origin|beginning|start|commencement|initiation|launch|debut|premiere|opening|unveiling|reveal|disclosure|exposure|discovery|detection|identification|recognition|acknowledgment|acceptance|approval|endorsement|support|backing|sponsorship|patronage|advocacy)(?:\s|$)/gi
};
